### ISSUE TITLE
VPN (SSL) should be included in NSX Base edition.

### ISSUE THREAD

**Issue by khayama** [IBM-Bluemix-Docs/vmwaresolutions#105]
VPN (SSL) should be included in NSX Base edition.
![170427 nsx base comparison matrix](https://user-images.githubusercontent.com/13445142/42024853-174b3ea6-7afe-11e8-9dba-e926da8336c9.png)

**Comment by delia-rusu** [comment]
Issue fixed on the staging (internal) environment.

**Comment by delia-rusu** [comment]
Fixed: https://console.stage1.bluemix.net/docs/services/vmwaresolutions/archiref/solution/appendix.html#comparison-chart-for-vmware-component-editions
