### ISSUE TITLE
The HCM requirement of the public connectivity for on-prem environment

### ISSUE THREAD

**Issue by khayama** [IBM-Bluemix-Docs/vmwaresolutions#62]
What's the correct requirement?
Is the global IP required to connect to the cloud?
Is the NATed IP okay for the public connectivity to the cloud?
How many IPs does the customer need to prepare for it?

**Comment by khayama** [comment]
Could you follow it up?

**Comment by delia-rusu** [comment]
@khayama sorry for the delay. Can you provide the specific URL of the documentation topic you are referring to? Thanks!

**Comment by khayama** [comment]
This URL
https://console.bluemix.net/docs/services/vmwaresolutions/services/hcx_considerations.html#considerations-for-hcx-on-ibm-cloud

**Comment by ClaireZheng** [comment]
1. FYI, considerations/requirements for the on-premises environment can be found in [this topic](https://console.bluemix.net/docs/services/vmwaresolutions/services/standalone_considerations.html#considerations-for-on-premises-hcx-instances). 
2. As for the IP requirements, clients need 3+ private IPs and a way for those IPs to connect to the public network.
