### ISSUE TITLE
The Cloud Foundation BOM seems incorrect

### ISSUE THREAD

**Issue by jharlow1** [IBM-Bluemix-Docs/vmwaresolutions#85]
It specifies that 3 VLANs are created (one public, 2 private)...but when I spun up a small instance in LON06, 5 VLANs were created (2 public, 3 private).

Also, it would be very helpful if all of the subnets, etc that got created had Notes populated in the SoftLayer console (e.g. reserved for VSAN (instance X), reserved for vMotion (instance x), etc).

**Comment by jharlow1** [comment]
Also, if the subnets could also be added to the BOM it would be helpful in understanding what all is created (especially useful when one already has dozens of subnets in SoftLayer and needs to determine what's what)

**Comment by robleyhall** [comment]
@delia-rusu I'll do some research on this, this is not the expected behavior.

**Comment by delia-rusu** [comment]
Not a doc issue, therefore closing. Opened internal git issue for investigation https://github.ibm.com/tornado/tracker/issues/9268
