### ISSUE TITLE
Problem with 'What to do Next'

### ISSUE THREAD

**Issue by jamesbeltonIBM** [IBM-Bluemix-Docs/vmwaresolutions#920]
The documentation for VMWare is winding and confusing. For example, on https://cloud.ibm.com/docs/services/vmwaresolutions?topic=vmware-solutions-getting-started#getting-started it states that Firefox, Chrome and Safari are the supported browsers and that Internet Explorer is not. However, once I have created my vCentre instance and want to log into the vCentre Console, the instructions here in the 'What to Do Next' section talks about logging into the datacentre VPN. While there is a link to the site, this seems to be a *really old* Softlayer vpn capability which relies on java (no longer supported in many browsers including Firefox and Chrome) and a relies on a further plug-in which is not supported by Safari. Net result is that it looks as though I can't do anything with my service from my Mac and have had to dig out a Windows laptop that I happen to have in the house to carry on, where I can use Internet Explorer to log into the VPN, though it's not explained WHY I need to log into the VPN to run the vCentre console.  What would happen if I had no access to any other PC/laptop? This is possibly more of a technical issue than a documentation one but the documentation could help here by saying what browsers / OSes are supported here as I have had to work this out for myself. 
The documentation generally isn't very helpful here as it doesn't really go into detail on the next steps - for example, at https://cloud.ibm.com/docs/services/vmwaresolutions/vcenter?topic=vmware-solutions-trbl_timeout_vc_console#trbl_timeout_vc_console, it states that I need to "Add the IP address and the host name mapping of PSC (Platform Services Controller) into the hosts file ..." - what hosts file?! Is this in the host of the local PC that I am using or somewhere else?
Also, the documentation keeps referencing 'the infrastructure console' and seems to be at odds with the cloud.ibm.com console.

**Comment by delia-rusu** [comment]
Hi James @jamesbeltonIBM thanks for your feedback. There is a difference between the IBM Cloud console and the IBM Cloud infrastructure console, see https://test.cloud.ibm.com/docs/customer-portal?topic=customer-portal-customerportal_whatisCP#customerportal_whatisCP

I'm also looking into the other issues reported.

**Comment by delia-rusu** [comment]
@jamesbeltonIBM Steps 1c and 1d are updated: https://test.cloud.ibm.com/docs/services/vmwaresolutions/services?topic=vmware-solutions-trbl_timeout_vc_console#trbl_timeout_vc_console-resolution
