### ISSUE TITLE
Sentence fragment

### ISSUE THREAD

**Issue by stephenrjr** [IBM-Bluemix-Docs/vmwaresolutions#931]
First sentence below needs to be evaluated as part of the next sentence:

"While vCenter Server instances enable the use of software defined networking. Any network overlays created by NSX that include routing to VLAN subnets aren't known by the IBM Cloud-managed routers and you might need to create static routes, firewall rules, and NAT rules to properly manage the network flows."

**Comment by delia-rusu** [comment]
Thanks for your feedback. Issue is tracked internally in https://github.ibm.com/tornado/tracker/issues/16176
