### ISSUE TITLE
Proper noun?

### ISSUE THREAD

**Issue by stephenrjr** [IBM-Bluemix-Docs/vmwaresolutions#932]
Consider cap "I" on Internet.

"This must be maintained as any changes might cause packet fragmentation over the internet."

**Comment by delia-rusu** [comment]
Thanks so much for your feedback. "internet" is correct per IBM Terminology guidelines: https://w3.ibm.com/standards/terminology/cgi-bin/lookup?11=main+form&11=acronym~abbreviation&11=prohibited&term=internet&submit=Search&source=en&db_name=LOGOS&pickDB=LOGOS&template=details&ug=corporate&target_switch=none&exact=on
