### ISSUE TITLE
Offering name incorrect

### ISSUE THREAD

**Issue by stephenrjr** [IBM-Bluemix-Docs/vmwaresolutions#933]
Please see https://cloud.ibm.com/docs/infrastructure/direct-link?topic=direct-link-overview-of-direct-link-offerings for the use of the "Direct Link" product offerings.

"All accounts with Direct-Link connections must be converted to, or created as, a VRF account."

**Comment by delia-rusu** [comment]
Thanks for your feedback. Issue is tracked internally in https://github.ibm.com/tornado/tracker/issues/16176
