### ISSUE TITLE
No vMotion Checklist Documentation

### ISSUE THREAD

**Issue by khayama** [IBM-Bluemix-Docs/vmwaresolutions#935]
There is no guide to check the vMotion compatibility between on-premise and cloud.
Please clarify which technical requirements is needed for the live migration between on-premise and cloud.
You should mention about the Intel CPU patch level, EVC mode, moving forward and backward, and the status after rebooting as the following link.

Migrating Virtual Machines : https://docs.vmware.com/en/VMware-Cloud-on-AWS/services/com.vmware.vmc-aws-operations/GUID-6EC9D234-6B9D-4C66-9385-D6AB3BFFFBC9.html
Hybrid Migration with vMotion Checklist : https://docs.vmware.com/en/VMware-Cloud-on-AWS/services/com.vmware.vmc-aws-operations/GUID-1A175E91-2317-4261-A63E-B398D92ECE8D.html

**Comment by delia-rusu** [comment]
I checked with the technical owner of this document; his answer: "The requested updates aren't in scope for this document. EVC is part of vCenter Server deployment with or without hybridity (HCX)."

**Comment by khayama** [comment]
@delia-rusu How can I request this kind of the new documentation?
